### ISSUE TITLE
question regarding circular reference in the model

### ISSUE THREAD

**Issue by darkKnight1** [awslabs/dynamodb-data-mapper-js#102]
I have a scenario where I need to have a circular reference in the model. 

I am designing a model to store responses to a survey where an answer to a question can be the answers to a series of questions.

Below is a sample input:

[ {  "question": "describes how, during the past 24 hours, fatigue has interfered with your",
	   "answer":[ {
                "question": "Mood",
                 "answer":[{"value":"Completely Interferes"}]         },
        	 {                "question": "Walking",
                 "answer":[{"value":"Interferes"}]              }           ]    } ]

I am not able to create a model to support this type of input. It throws "'TypeError: Cannot read property \'prototype\' of undefined'" error.
Attached the JSON schema for the input and my model.

Could you please explain how can I implement this schema in the model.

[jsonSchema.txt](https://github.com/awslabs/dynamodb-data-mapper-js/files/2307314/jsonSchema.txt)

[Model.txt](https://github.com/awslabs/dynamodb-data-mapper-js/files/2307390/Model.txt)

**Comment by jeskew** [comment]
There's a test to verify that the [schema format supports recursion](https://github.com/awslabs/dynamodb-data-mapper-js/blob/master/packages/dynamodb-data-marshaller/src/SchemaType.spec.ts#L272) and a [more extensive recursion test](https://github.com/awslabs/dynamodb-data-mapper-js/blob/master/packages/dynamodb-data-mapper/src/DataMapper.integ.ts#L11) in the data mapper's integration suite.

I think the issue that you're seeing is that the `Answer` constructor does not exist when the `Item` class is being defined. (Unlike named functions, classes must be defined before use.) I think you will need to manually attach a schema to the classes rather than using annotations:

```typescript
class Item {
    Id: string;
    text?: string;
    answer?: Answer[];
    item?: Item[];
}

class Answer {
    value?: string;
    item?: Item[];
}

const itemSchema: Schema = {
    Id: {
        type: 'String',
        keyType: 'HASH'
    },
    text: { type: 'String' },
};
const itemList: SchemaType = {
    type: 'List',
    memberType: {
        type: 'Document'
        valueConstructor: Item,
        members: itemSchema,
    },
};
itemSchema.item = itemList;

const answerSchema = {
    value: {type: 'String'},
    item: itemList
};
itemSchema.answer = {
    type: 'List',
    memberType: {
        type: 'Document'
        valueConstructor: Answer,
        members: answerSchema,
    },
}

Object.defineProperties(Item.prototype, {
    [DynamoDbTable]: {value: "Response"},
    [DynamoDbSchema]: {value: itemSchema},
});
Object.defineProperties(Answer.prototype, {
    [DynamoDbSchema]: {value: answerSchema},
});
```

**Comment by darkKnight1** [comment]
Thank You. It worked. 👍
