### ISSUE TITLE
Working example

### ISSUE THREAD

**Issue by dragosbulugean** [awslabs/dynamodb-data-mapper-js#28]
I am having trouble using this with TS.
Can we provide a working example with proper tsconfig.json?
I have experimentalDecorators and emitDecoratorMetadata on, and imported "reflect-metadata", and I still get this: 
```
Error: Properties of type Any may not be used as index or table keys. If you are relying on automatic type detection and have encountered this error, please ensure that the 'emitDecoratorMetadata' TypeScript compiler option is enabled. Please see https://www.typescriptlang.org/docs/handbook/decorators.html#metadata for more information on this compiler option.
```

**Comment by dragosbulugean** [comment]
Made it work. Date rangeKeys should always specify 'keyType' and 'type', otherwise you get runtime errors.

**Comment by jeskew** [comment]
There is a working example in [a functional test](https://github.com/awslabs/dynamodb-data-mapper-js/blob/v0.4.0/packages/dynamodb-data-mapper-annotations/src/functional.spec.ts#L80), but that can be difficult to find. I've opened a PR to move that example schema to its own file to make it more discoverable.

Was the code triggering the error pasted above using a property initialized to a date rather than annotated as a date? There seems to be a quirk (or bug) in TypeScript's emitted type metadata where initialized properties are reported to be of type `Object`, even when the emitted type declarations correctly infer the desired type.

This is what I found with TypeScript 2.6.2:

* Declaring a property with a type annotation and no initial value, e.g., 

    ```typescript
    @table('Foos')
    class Foo {
        @rangeKey()
        createdAt: Date;
    }
    ```

    will cause the property to receive a decorator that declares its type to be `Date` in the compiled output:

    ```javascript
    var Foo = /** @class */ (function () {
        function Foo() {
        }
        tslib_1.__decorate([
            _1.rangeKey(),
            tslib_1.__metadata("design:type", Date)
        ], Foo.prototype, "createdAt", void 0);
        Foo = tslib_1.__decorate([
            _1.table('Foos')
        ], Foo);
        return Foo;
    }());
    ```

* Declaring a property with an initial value and no type annotation, e.g.,
  
    ```typescript
    @table('Foos')
    class Foo {
        @rangeKey()
        createdAt = new Date;
    }
    ```

    will, however, lead the emitted metadata to report the property's type as `Object`:

    ```javascript
    var Foo = /** @class */ (function () {
        function Foo() {
            this.createdAt = new Date;
        }
        tslib_1.__decorate([
            _1.rangeKey(),
            tslib_1.__metadata("design:type", Object)
        ], Foo.prototype, "createdAt", void 0);
        Foo = tslib_1.__decorate([
            _1.table('Foos')
        ], Foo);
        return Foo;
    }());
    ```

Both TypeScript examples emit the same declaration, which correctly identifies the `createdAt` field as being of type `Date`. I'll open an issue with TypeScript to see if this is a bug or intended behavior.

**Comment by dragosbulugean** [comment]
I had

```
@rangeKey({defaultProvider: () => new Date()})
createdAt: Date;
```

It worked was after I changed it to:

```
@rangeKey({
    type: "Date"
    defaultProvider: () => new Date()
})
createdAt: Date;
```

**Comment by dragosbulugean** [comment]
Great job BTW! This is a pretty good wrapper.

**Comment by jeskew** [comment]
Total stab in the dark here, but is the constructor crossing realm boundaries? Types are detected using `===` and `instanceof`, which won't work if the `Date` constructors being compared are from different iframes or Node VMs.

**Comment by chanlito** [comment]
Any examples with the serverless framework?

**Comment by jeskew** [comment]
There are no framework-specific bindings in this package, so the examples in the README would be applicable to use with Serverless
