### ISSUE TITLE
Support for dynamoDB doc client?

### ISSUE THREAD

**Issue by kichooo** [awslabs/dynamodb-data-mapper-js#30]
Would be really useful. Currently it is not compatible: 

`TypeError: this.client.batchGetItem is not a function`

docClient has only batchGet

**Comment by jeskew** [comment]
Hi @kichooo,

You would use the data mapper instead of the doc client. Both projects will convert regular JS values into DynamoDB AttributeValues, but the data mapper uses a schema while the doc client does runtime type inference. You can provide the doc client's underlying service object ([`docClientInstance.service`](https://github.com/aws/aws-sdk-js/blob/v2.184.0/lib/dynamodb/document_client.js#L96)) to the DataMapper constructor if you want to share the same low-level service client.

**Comment by kichooo** [comment]
Thank you for the response, will give it a try in few days, as now I had to settle for semi-satisfying solution with combined approach. 

Closing for now
