### ISSUE TITLE
Is there a way to get the LastEvaluatedKey?

### ISSUE THREAD

**Issue by phstc** [awslabs/dynamodb-data-mapper-js#58]
Hey!

I'm implementing a regular in-browser pagination: list 10 items, click next, go to the next page.

For paginating to the next page I need to set the `startKey` with the `lastEvaluatedKey` from the previous page. I'm currently, generating the `lastEvaluatedKey` programmatically, since I know what are the keys, but I'm wondering if there's a way to retrieve it from the query result, since the SDK returns it.

Is there a way to get the `lastEvaluatedKey` from the query result?

**Comment by jeskew** [comment]
Since `query` is returning an async iterable instead of an object, supporting that access pattern might require adding a separate method with a different return signature. 

One alternative would be to always include a the last evaluated key in the `IteratorResult` that signals completion, but those results are discarded by `for await ... of` loops. Would it be a deal-breaker if you had to use the iterator protocol directly in order to access the last evaluated key?

**Comment by phstc** [comment]
Hi @jeskew 

> Would it be a deal-breaker if you had to use the iterator protocol directly in order to access the last evaluated key?

You mean like that?

```javascript
for await (const item of iterator) {
  items.push(item)

  if (items.length > limit) {
    break
  }
}

// HERE???
const lastKey = iterator.lastKey
```

If so, that would work for me.  `lastKey` would be `null` if there's no next records, right?

**Comment by jeskew** [comment]
Right, something like that. Another thought is that I could use the last `IteratorResult` to communicate the last key. Essentially, the query runner would do something like this:

```typescript
async function *runQuery(params) {
    const {Items, LastEvaluatedKey} = await cilent.query(params).promise();
    for (const item of Items) {
        yield item;
     }
     return LastEvaluatedKey;
}
```

So if a query page contained two results, three calls to `runQuery(params)().next()` would return:

```
> {value: item, done: false}
> {value: item, done: false}
> {value: LastEvaluatedKey, done: true}
```

The trouble with that is that `for ... of` loops will ignore the last value, so you would need to use the `.next` method directly in order to see the last key.

**Comment by phstc** [comment]
@jeskew something like that 👇?

```es6
let items = []

let item = await query.iterator.next()

while (!item.done) {
  items.push(item.value)

  if (items.length > limit) {
    break
  }

  item = await query.iterator.next()
}

const lastKey = await query.iterator.next().value
````

**Comment by jeskew** [comment]
Very close to that, but you wouldn't want to call `next()` again after `item.done` was detected to be `true`:

```javascript
let items = []
let query = mapper.query(Constructor, {hashKey: 'value'});

let item = await query.next()
while (!item.done) {
  items.push(item.value)

  if (items.length > limit) {
    item = await query.return(); // for await ... of loops call `.return` automatically
    break
  }

  item = await query.next()
}

const lastKey = item.value
```

It's a lot more boilerplate than a `for` loop, and the fact that calling `next` any additional times would return `{value: undefined, done: true}` makes it seem fragile. The fact that you also need to [manually close the iterator](http://raganwald.com/2017/07/22/closing-iterables-is-a-leaky-abstraction.html) is not ideal. 

The only advantage to this approach vs the one you proposed is that I would be able to continue using async generators instead of writing a custom async iterable. I think something closer to what you propose [above](https://github.com/awslabs/dynamodb-data-mapper-js/issues/58#issuecomment-391670803) is the right way to solve this.

**Comment by jeskew** [comment]
This was added in 0.6.0. To get the last evaluated key, you will need to use the paginator rather than the iterator:

```typescript
const paginator = mapper.query(MyClass, key, {limit: 25}).pages();

for await (const page of paginator) {
   // page is an array of records
}

console.log(paginator.lastEvaluatedKey);
```

The attributes that must be specified for the `startKey` value when querying or scanning an index cannot always be predicted, so `lastEvaluatedKey` is not available on the iterator but only on the paginator (which always knows the `LastEvaluatedKey` returned by the last request to DynamoDB).

**Comment by LucasBadico** [comment]
@jeskew Me again. This just Aswer the last question. I was thinking on use the generators like in your example.
