### ISSUE TITLE
Wrong start key for GSIs

### ISSUE THREAD

**Issue by antogyn** [awslabs/dynamodb-data-mapper-js#65]
Hey,

To handle pagination on a GSI, DynamoDB needs primary keys of both the table and the GSI, but the marshalling function strips the table keys:

https://github.com/awslabs/dynamodb-data-mapper-js/blob/0912ab9cdb63803ca737debbc28fbb4357ca3765/packages/dynamodb-data-mapper/src/DataMapper.ts#L855

Which returns `Exclusive Start Key must have same size as table's key schema`

Of course the ideal solution would be to directly access and pass the `LastEvaluatedKey`

**Comment by jeskew** [comment]
According to [the DynamoDB guide on secondary indices](https://docs.aws.amazon.com/amazondynamodb/latest/developerguide/SecondaryIndexes.html), GSI keys do not need to overlap with the table keys at all.

Have you modeled all the keys of the index being queried?

**Comment by antogyn** [comment]
The `LastEvaluatedKey` contains both the table keys and the GSI keys

**Comment by jeskew** [comment]
I did a bit of experimentation and found that while `LastEvaluatedKey` typically contains the table and index keys, the exact keys returned are not uniform across multiple queries of the same index. According to [this AWS forum post](https://forums.aws.amazon.com/thread.jspa?threadID=146102&tstart=0), only `LastEvaluatedKey`s returned from previous requests on the same index are officially accepted as `ExclusiveStartKey` values.

Both `query` and `scan` will need to be updated to marshall the values provided instead of the keys defined.
