### ISSUE TITLE
Read all results in one call (for API responses)

### ISSUE THREAD

**Issue by kennu** [awslabs/dynamodb-data-mapper-js#7]
The `for async` syntax is a nice way to hide lastEvaluatedKey/exclusiveStartKey. But when returning data from an API, it involves a clumsy need to do something like:

    const items = []
    for async (const item of dynamo.query(...)) {
      items.push(item)
    }
    return items

So I'm wondering if it would be possible to add some simple way to read all the results using a single function call? Something like:

    return await readAll(dynamo.query())

I am also slightly worried about the performance implications of async iterators, if every item is resolved as a separate promise?

Btw, overall I am really excited about the whole dynamodb-data-mapper library. Having written a lot of code using AWS.DynamoDB.DocumentClient, I appreciate how this library solves many painful things in it. 👍

**Comment by jeskew** [comment]
I agree that you shouldn't have to repeat boilerplate when using async iterators, but what would you think about instead having a function that collects an async iterator in an array, e.g.:

```typescript
async function collect<T>(iter: AsyncIterator<T>): Promise<Array<T>> {
    const results: Array<T> = [];
    for await (const element of iter) {
        results.push(element);
    }
    return results;
}
```

That seems like the kind of utility that belongs in a lodash-style library for working with iterators and async iterators, but I'm having trouble finding something that fits that bill.

**Comment by kennu** [comment]
Yeah, I guess it would be typical to use a third party utility library. OTOH it would be too bad if there is no built-in way in dynamodb-data-mapper to read the whole response, because about 99% of my use cases are exactly that.

**Comment by jeskew** [comment]
I understand what you mean, but I would be worried about providing a method that greedily scans an entire table due to the performance impact that can have on large tables with limited read capacity. The motivation behind using async iterators for querying and scanning is that you can break out of the loop at any point, and ending iteration early will cause fewer requests to be sent and less read capacity to be consumed.

I couldn't find a lodash-style utility library for working with async iterators, so I put together [one that will support basic filtering, mapping, reducing, etc.](https://www.npmjs.com/package/@jsq/async-seq). It includes a `collect` function that does what you're looking for:

```typescript
import {DataMapper} from '@aws/dynamodb-data-mapper';
import {collect} from '@jsq/async-seq';

// ... setup code etc.

const allScannedResults: Array<MyDomainObject> = await collect(mapper.scan(params));
```

That may be slightly more overhead than a `scanAll` method, but it makes the intent clear.

**Comment by jeskew** [comment]
This was added in 0.6.0. To get batches of results instead of an item-by-item iterator, use the `.pages` method of the object returned by `mapper.query` to get a paginator:

```typescript
const paginator = mapper.query(MyClass, key, {limit: 25}).pages();

for await (const page of paginator) {
   // page is an array of records
}
```

Each page corresponds to a response from DynamoDB, so you may get multiple arrays back before hitting the specified `limit`.
