### ISSUE TITLE
mapper.put not return objectId

### ISSUE THREAD

**Issue by ricardwrodrigues** [awslabs/dynamodb-data-mapper-js#9]
Hello, I'm using with serverless and when I'm trying to mapper.put () this is not returning object. See my example thanks.

export async function createArtist(args) {
  const artist = new Artist();
  artist.firstName = args.first_name;
  artist.lastName = args.last_name;
  return await new Promise((resolve, reject) =>
    mapper.put({item: artist})
      // tslint:disable-next-line:arrow-parens
      .then(data => resolve(data))// data is undefined
      // tslint:disable-next-line:arrow-parens
      .catch(err => reject(err)),
    );
}

@table("artists")
class Artist {

    @autoGeneratedHashKey()
    @attribute({keyType: "HASH"})
    public id: string;

    @attribute()
    public firstName: string;

    @attribute()
    public lastName: string;
}

**Comment by jeskew** [comment]
You have a good point; since marshalling is doing more than just a simple transformation (it's injecting UUIDs and other defaults, normalizing parameters, incrementing version numbers, etc), calling code needs access to the object that was saved to DynamoDB. 

This will be a breaking change if anyone was using the `returnValues` parameter on `put` to disable getting a response or if anyone was relying on the default return value being the object that was overwritten, but the current return has a pretty big usability problem.
